[build]
  command = "npm run build && mkdir -p dist/functions && cp -r dist/portfolio/server/* dist/functions/ && mv dist/functions/main.server.mjs dist/functions/main-server.mjs && mv dist/functions/polyfills.server.mjs dist/functions/polyfills-server.mjs"
  publish = "dist/portfolio/browser"

[functions]
  directory = "dist/functions"
  node_bundler = "esbuild"
  included_files = ["**/*"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
  force = false
  
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin" 