# ============================================
# Configuración Netlify - Patrón Modular
# ============================================
# Configuración optimizada para Angular 19 + SSR
# Usa @netlify/angular-runtime para manejo nativo

[build]
  command = "npm run build"
  publish = "dist/portfolio/browser"

# ============================================
# Configuración de Headers - Seguridad
# ============================================
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

# ============================================
# Configuración de Headers - Assets Estáticos
# ============================================
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# ============================================
# Configuración de Headers - Archivos JS/CSS
# ============================================
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# ============================================
# Redirects - SPA y Angular Universal
# ============================================
# Manejo de rutas SPA para Angular
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
  force = false

# ============================================
# Configuración de Build - Optimización
# ============================================
[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10" 